[package]
name = "oxide-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]
bootloader = { version = "0.9.29", features = ["map_physical_memory"] }
spin = "0.9.8"
x86_64 = "0.15.5"

[[bin]]
name = "oxide-kernel"
test = false
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
